buildscript {
    // Kita tetapkan versi Kotlin standard untuk kestabilan
    ext.kotlin_version = '1.7.10'
    repositories {
        // ✅ STRATEGI FRANCOIS: Google MESTI duduk atas sekali
        // Ini memaksa sistem cari di Google dulu, elak error 403 Maven
        google()
        mavenCentral()
    }

    dependencies {
        // Ini adalah versi yang Kapten perlukan (berdasarkan error log tadi)
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        // ✅ STRATEGI SAMA: Ulang google() di atas juga di sini
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
